export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const ADD_API_DATA = 'ADD_API_DATA';
export const FETCH_API_FAILURE = 'FETCH_API_FAILURE';
export const FETCH_API_REQUEST = 'FETCH_API_REQUEST';
export const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS';
export const SELECT_CURRENT_CHARACTER = 'SELECT_CURRENT_CHARACTER';